### ISSUE TITLE
Classroom TODO

### ISSUE THREAD

**Issue by zmwebdev** [zmwebdev/python-course#3]
python:
- [ ] OOP: classes, ...
- [ ] scopes: 
      - https://github.com/zmwebdev/python/blob/master/test/scopes.py
      - https://github.com/zmwebdev/python/blob/master/test/scopes2.py
- [ ] errors: https://docs.python.org/3/tutorial/errors.html
- [ ] virtualenv (?)

Renfe:
- [ ] Flask intro
- [ ] Convert to OOP using Classes
- [ ] error. Try, except
- [x] Put functions into a file and then import
- [x] json.dump(), json.load()
- [x] create functions to manage data. Zones, poblation, ...

Python IDE:
- [ ] yUML: https://marketplace.visualstudio.com/items?itemName=JaimeOlivares.yuml
- [ ] IDLE: clear screen
- [x] git config using VSCode. Clone the repo in a directory and then open this dir. If user config changed, put all config in "user setting" in order "workspace"
- [x] user settings vs workspace settings
- [x] debug terminal-console apps
- [x] VSCode: iterative. Use input

**Comment by zmwebdev** [comment]
continue here: https://github.com/zubirimanteo/python-course/issues/2

**Comment by zmwebdev** [comment]
continue here: https://github.com/zubirimanteo/python-course/issues/2
